export const ROUTES = {
  home: "/",
  guides: "/poradniki",
  guideCategories: "/poradniki/kategorie",
  guideCategory: (categoryId: string) => `/poradniki/${categoryId}`,
  guideDetails: (id: string) => `/poradniki/poradnik/${id}`,
  favoriteGuides: "/poradniki/ulubione",
  dictionary: "/poradniki/slownik",
  map: "/mapa",
  mapPins: "/mapa/pinezki",
  notes: "/notatnik",
  newNote: "/notatnik/nowa-notatka",
  noteDetails: (id: string) => `/notatnik/${id}`,
  emergency: "/alarmowe",
  tools: "/narzedzia",
  compass: "/narzedzia/kompas",
  sos: "/narzedzia/sos",
  admin: "/admin",
  addGuide: "/admin/dodaj-poradnik",
  editGuide: (id: string) => `/admin/edytuj-poradnik/${id}`,
} as const;
